// Downloads one photo per canonical product, compresses to local WebP.
// Usage: node images.cjs  (reads lib/data/live-images-src.json from bake.cjs)
const fs = require("fs");
const sharp = require("sharp");

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) DZPartPicker-bot/0.1";

async function dl(id, url) {
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), 20000);
  try {
    const r = await fetch(url, { headers: { "User-Agent": UA }, signal: ctl.signal });
    const ct = r.headers.get("content-type") || "";
    if (!r.ok || !ct.startsWith("image")) return false;
    const buf = Buffer.from(await r.arrayBuffer());
    await sharp(buf).resize(256, 256, { fit: "cover" }).webp({ quality: 65 }).toFile(`public/p/${id}.webp`);
    return true;
  } catch {
    return false;
  } finally {
    clearTimeout(t);
  }
}

async function main() {
  const src = JSON.parse(fs.readFileSync("lib/data/live-images-src.json", "utf8"));
  fs.mkdirSync("public/p", { recursive: true });
  const ids = Object.keys(src);
  const map = {};
  let i = 0;
  async function worker() {
    while (i < ids.length) {
      const id = ids[i++];
      if (await dl(id, src[id])) map[id] = `/p/${id}.webp`;
      else console.log("  skip (no image):", id);
    }
  }
  await Promise.all(Array.from({ length: 5 }, worker));
  const out = `// AUTO-GENERATED by images.cjs — one compressed local photo per product.\nexport const LIVE_IMAGES: Record<string, string> = ${JSON.stringify(map, null, 2)};\n`;
  fs.writeFileSync("lib/data/live-images.ts", out);
  console.log(`photos: ${Object.keys(map).length}/${ids.length}`);
}

main();
